SHAVIRA FEBYNADIA
222410101020
# LKM 1

In [ ]:
# Buatlah array 2D berikut menggunakan numpy

import numpy as np
array_2D = np.array([[4, 4, 5],
                     [7, 6, 4],
                     [9, 7, 4],
                     [6, 3, 7]])
print(array_2D)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


In [ ]:
# Buatlah array 3D berikut menggunakan numpy

array_3D = np.array([[7, 8, 5, 2, 1, 2, 2, 9, 3, 4, 7, 7, 9, 8, 5, 2, 4, 8, 7, 1, 9, 3, 7, 3, 1, 6, 6, 5, 4, 10, 4, 9, 9, 8, 1, 3]]).reshape(3, 4, 3)
print(array_3D)


[[[ 7  8  5]
  [ 2  1  2]
  [ 2  9  3]
  [ 4  7  7]]

 [[ 9  8  5]
  [ 2  4  8]
  [ 7  1  9]
  [ 3  7  3]]

 [[ 1  6  6]
  [ 5  4 10]
  [ 4  9  9]
  [ 8  1  3]]]


In [ ]:
#Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut

import numpy as np

# Matriks untuk menyimpan nilai gambar
arr2d = np.array([
    [1, 8, 8, 2],
    [8, 2, 1, 2],
    [10, 1, 4, 7],
    [1, 4, 7, 8],
    [8, 2, 3, 4],
])

# Mencetak kode 2D
print("Sebelum Ditambah\n")
print(arr2d)

# Menambahkan 1 pada setiap bilangan di baris ganjil
arr2d[1::2] += 1 #Menambahkan 1 pada setiap elemen di baris ganjil (indeks dimulai dari 1 dengan selang 2).

# Menambahkan 2 pada setiap bilangan di kolom genap
arr2d[:, ::2] += 2 #Menambahkan 2 pada setiap elemen di kolom genap (indeks dimulai dari 0 dengan selang 2).

# Mencetak hasil setelah penambahan
print("\n|Setelah Ditambah|\n")
print(arr2d)


Sebelum Ditambah

[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]

|Setelah Ditambah|

[[ 3  8 10  2]
 [11  3  4  3]
 [12  1  6  7]
 [ 4  5 10  9]
 [10  2  5  4]]


In [ ]:
# Baliklah sumbu z array 3D berikut

arr3d = np.array([[7, 8, 5, 4, 7, 7, 7, 1, 9, 5, 4, 10, 2, 1, 2, 9, 8, 5, 3, 7, 3, 4, 9, 9, 2, 9, 3, 2, 4, 8, 1, 6, 6, 8, 1, 3]]).reshape(3, 4, 3)
print("Sebelum\n")
print(arr3d)
arr3d = np.flipud(arr3d)
print("\nSetelah dibalik\n")
print(arr3d)

Sebelum

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]

Setelah dibalik

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


In [ ]:
# Ubahlah array pada soal 4 menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah reshape)

arr2d = arr3d.reshape(6, 6)
print("Ini adalah array 2D dengan ukuran 6x6:")
print(arr2d)




Ini adalah array 2D dengan ukuran 6x6:
[[ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]]


In [ ]:
import numpy as np

arr6a = np.array([5, 10, 10, 7, 7, 8, 4, 10, 9, 10, 2, 5, 1, 8, 9, 3, 6, 10, 5, 2, 4, 6, 9, 4]).reshape(6,4)
print("Ubahlah matrix kiri menjadi matrix sebelah kanan\n")
print(arr6a)

# Memisahkan 4 kolom menjadi 2 kolom
kiria, kanana = np.hsplit(arr6a, 2) #memisahkan matrik menjadi 2 bagian

# Menukar matriks yang terpisah
arr6a = np.concatenate((kanana, kiria), axis=1) #digabungkan secara horizontal, dengan dibagi dengan masing masing kolom yang sama , kalo misal axis = 0 itu barisnya yang sama

print("\n{SETELAH DIUBAH}\n")
print(arr6a)


Ubahlah matrix kiri menjadi matrix sebelah kanan

[[ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]
 [ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]]

{SETELAH DIUBAH}

[[10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]
 [ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]]


In [ ]:
import numpy as np

arr6b = np.array([9, 3, 1, 8, 5, 2, 6, 10, 9, 4, 4, 6, 10, 7, 5, 10, 4, 10, 7, 8, 2, 5, 9, 10]).reshape(6,4)
print("Ubahlah matrix kiri menjadi matrix sebelah kanan\n")
print(arr6b)

# Memisahkan 4 kolom menjadi 2 kolom
kirib, kananb = np.hsplit(arr6b, 2) #memisahkan matrik menjadi 2 bagian

# Menukar matriks yang terpisah
arr6b = np.concatenate((kananb, kirib), axis=1) #digabungkan secara horizontal, dengan dibagi dengan masing masing kolom yang sama , kalo misal axis = 0 itu barisnya yang sama

print("\n{SETELAH DIUBAH}\n")
print(arr6b)


Ubahlah matrix kiri menjadi matrix sebelah kanan

[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]

{SETELAH DIUBAH}

[[ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]
 [ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]]
